const CartAct = {
    TOGGLE_CART: 'TOGGLE_CART',
    ADD_ITEMS: 'ADD_ITEMS',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM:'REMOVE_ITEM',
    CLEAR_CART:'CLEAR_CART'
  };
  
  export default CartAct;